[package]
name = "mofliplib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde-redis = "0.13.0"
r2d2_redis = "0.14.0"
redis = "0.22.3"
thiserror = "1.0.30"
scylla = "0.10"
anyhow = "1.0.75"